version: "3.5"
services:
  backend:
    build:
      context: ./
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-AKIAIOSFODNN7EXAMPLE}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules:delegated
    environment:
      - NODE_ENV=development
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-dev}
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: yarn dev
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    ports:
      - 3001:8000